# Elasticsearch deployment itself
apiVersion: apps/v1
kind: StatefulSet
#kind: Deployment
metadata:
  name: {{ .Values.elastic.name }}
  #namespace: kube-system
  labels:
    k8s-app: {{ .Values.elastic.name }}
    version: v7.4.2
spec:
  serviceName: {{ .Values.elastic.name }}
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      k8s-app: {{ .Values.elastic.name }} 
      version: v7.4.2
  template:
    metadata:
      labels:
        k8s-app: {{ .Values.elastic.name }}
        version: v7.4.2
    spec:
      serviceAccountName: {{ .Values.serviceAccount.elastic_sa }}
      containers:
      - image: {{ .Values.elastic.image }}
        name: {{ .Values.elastic.name }}
        ports:
        - containerPort:  {{ .Values.elastic.port }}
          name: db
          protocol: TCP
        - containerPort:  {{ .Values.elastic.transport_port }}
          name: transport
          protocol: TCP
        volumeMounts:
        - name: {{ .Values.elastic.name }}
          mountPath: /data
        env:
        - name: "NAMESPACE"
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
      volumes:
      - name: {{ .Values.elastic.name }}
        persistentVolumeClaim:
          claimName: {{ .Values.elastic.storage_pvc }}    
      # Elasticsearch requires vm.max_map_count to be at least 262144.
      # If your OS already sets up this number to a higher value, feel free
      # to remove this init container.
      initContainers:
      - image: alpine:3.6
        command: ["/sbin/sysctl", "-w", "vm.max_map_count=262144"]
        name: elasticsearch-logging-init
        securityContext:
          privileged: true        