apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.elastic.name }}
  #namespace: kube-system
  labels:
    k8s-app: {{ .Values.elastic.name }}
    kubernetes.io/name: "Elasticsearch"
spec:
  ports:
  - port: {{ .Values.elastic.port }}
  type: ClusterIP 
  selector:
    k8s-app: {{ .Values.elastic.name }}