{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.ingress.name }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: {{ .Values.ingress.admin_host }} #for local use add these domain to your dns server for example sophos-network-dns-DNS Host Entry. 
      http:
        paths:
        - path: /
          backend:
            serviceName: {{ .Values.adminer.name }}
            servicePort: {{ .Values.adminer.port }}     
    - host: {{ .Values.ingress.elastic_host }} #for local use add these domain to your dns server for example sophos-network-dns-DNS Host Entry. 
      http:
        paths: 
        - path: /
          backend:
            serviceName: {{ .Values.elastic.name }}
            servicePort: {{ .Values.elastic.port }}                       
    #kibana is only working in rootpath of a domain
    - host: {{ .Values.ingress.kibana_host }} #for local use add these domain to your dns server for example sophos-network-dns-DNS Host Entry. 
      http:
        paths: 
        - path: /
          backend:
            serviceName: {{ .Values.kibana.name }}
            servicePort: {{ .Values.kibana.port }}   
    #grafana is only working in rootpath of a domain
    - host: {{ .Values.ingress.grafana_host }} #for local use add these domain to your dns server for example sophos-network-dns-DNS Host Entry. 
      http:
        paths: 
        - path: /
          backend:
            serviceName: monitoring-grafana
            servicePort: 80  

{{- end }}

